### ISSUE TITLE
Use of `capstone` with `frida-gum` causes UnsupportedArch error

### ISSUE THREAD

**Issue by CatMe0w** [capstone-rust/capstone-rs#162]
On Windows and macOS, when both the Rust crates `capstone` and `frida-gum` are used as dependencies, Capstone will consistently fail with `UnsupportedArch` error, even if `frida-gum` has not yet been initialized.

### Minimum reproducible code:

Cargo.toml:
```toml
[package]
name = "capstone-frida-bug-test"
version = "0.1.0"
edition = "2021"

[dependencies]
capstone = "0.12.0"
frida-gum = { version = "0.13.7", features = ["auto-download"] }
```

main.rs:
```rust
use capstone::prelude::*;

fn main() {
    let mut _cs = Capstone::new()
        .x86()
        .mode(arch::x86::ArchMode::Mode64)
        .syntax(arch::x86::ArchSyntax::Intel)
        .detail(false)
        .build()
        .unwrap();
    // let _gum = unsafe { frida_gum::Gum::obtain() };
}
```

This code will exit successfully. However, if you uncomment the `let _gum` line, Capstone will always fail during initialization.

This issue does not occur on Linux.

### On Windows:
```
   Compiling capstone-frida-bug-test v0.1.0 (C:\Users\CatMe0w\Desktop\capstone-frida-bug-test)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.23s
     Running `target\debug\capstone-frida-bug-test.exe`
thread 'main' panicked at src/main.rs:10:10:
called `Result::unwrap()` on an `Err` value: UnsupportedArch
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src\panicking.rs:652
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\panicking.rs:72
   2: core::result::unwrap_failed
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\result.rs:1679
   3: enum2$<core::result::Result<capstone::capstone::Capstone,enum2$<capstone::error::Error> > >::unwrap
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\result.rs:1102
   4: capstone_frida_bug_test::main
             at .\src\main.rs:4
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >  
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\ops\function.rs:250
   6: core::hint::black_box
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\hint.rs:338
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\capstone-frida-bug-test.exe` (exit code: 101)
```

### On macOS (ARM):
```
   Compiling capstone-frida-bug-test v0.1.0 (/Users/cat/capstone-frida-bug-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.67s
     Running `target/debug/capstone-frida-bug-test`
thread 'main' panicked at src/main.rs:10:10:
called `Result::unwrap()` on an `Err` value: UnsupportedArch
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: capstone_frida_bug_test::main
             at ./src/main.rs:4:19
   5: core::ops::function::FnOnce::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tmfink** [comment]
Thanks for reporting the issue!

I'm not familiar with frida-gum, but it looks like friday-gum links with the C capstone library. This can cause issues since code will expect to be calling into one version the Capstone C library, but will get the other.

Since this is a problematic issue, there is a "links" key in `Cargo.toml` that lets a crate declare that it links to a library.
When resolving dependencies, cargo enforces that only one crates is allowed to declare a given library links to a library in the dependency graph. If cargo sees multiple crates link to the same lib, then cargo will error out when building (to avoid confusing runtime issues).

Similar issue seen with conflicting bindings to the sqlite3 C library:
https://users.rust-lang.org/t/two-dependencies-linking-the-same-dynamic-library/100432

In our case, we can see that frida-gum C library links to Capstone:
https://github.com/frida/frida-gum/blob/25efdc99b005fdb59a136c1d6b96b3cddfea33de/subprojects/capstone.wrap

The `capstone-sys` library correctly declares that it links to `capstone` C library:
https://github.com/capstone-rust/capstone-rs/blob/4265854d41dad2102384d20d27f97a7fec8cfae9/capstone-sys/Cargo.toml#L9

But neither the `frida-sys` nor the `frida-gum-sys` crates declare that they link to any libraries:

https://github.com/frida/frida-rust/blob/2ee2acb3997ed6879634bad2743d2677589ac448/frida-sys/Cargo.toml
https://github.com/frida/frida-rust/blob/2ee2acb3997ed6879634bad2743d2677589ac448/frida-gum-sys/Cargo.toml

**Comment by tmfink** [comment]
It's *possible* that we could resolve some of these issues by renaming all of the Capstone symbols to avoid possible collisions with another instance of Capstone, but I'm not sure of a good way to rename all of the Capstone symbols in a portable, maintainable way.

Here is the build script where we build the Capstone C library:
https://github.com/capstone-rust/capstone-rs/blob/4265854d41dad2102384d20d27f97a7fec8cfae9/capstone-sys/build.rs

On Unix-like systems, we could use `objcopy` `--prefix-symbols` to add a unique prefix to all Capstone symbols which we then use in `capstone-sys`, but that would be a lot of work, would not be portable, and add a dependency on `objcopy`.

Since I'm not sure there is a good way to handle this issue, I'm closing this issue for now.
I can be convinced if someone has a good idea and/or has a PR implementing a fix.

**Comment by CatMe0w** [comment]
We found the same root cause later on, but we haven't come up with a good solution yet. Currently, our workaround is to split our code that uses Capstone and Frida into two separate crates to avoid linking both dependencies at the same time.
